### ISSUE TITLE
Bug: Missing field and expression documentation in the selectors docs

### ISSUE THREAD

**Issue by squeedee** [vmware-tanzu/cartographer-site#73]
[This section](https://cartographer.sh/docs/v0.1.0/architecture/#selectors) needs to include an explanation of selectorMatchFields and selectorMatchExpressions

**Comment by idoru** [comment]
Closing as I think https://cartographer.sh/docs/v0.3.0/architecture/#selectors now covers this well. Please re-open with more detail if necessary.
